FROM docker.wso2.com/wso2mi:1.2.0.0-alpine
 
LABEL image="Private Base Image"
 
# Copy resources if needed, Keystores etc.
#COPY resources/telstra.jks /home/wso2carbon/wso2mi-1.2.0/
 
# Add Remote resources if needed, common drivers etc.
# ADD http://source.file/url  /destination/path
